/**
 * seed.js - Mock safety data for Mumbai
 * Center: Mumbai (19.0760, 72.8777)
 * All coordinates are mock Mumbai landmarks.
 */

export const SEED_REPORTS = [
  {
    title: 'Broken streetlights near Bandra Kurla Complex',
    description: 'Three consecutive streetlights non-functional for 2+ weeks. Extremely dark after 8 PM.',
    category: 'broken_light',
    severity: 'high',
    latitude: 19.0667,
    longitude: 72.8645,
    upvotes: 14,
    status: 'municipal_notified',
    municipal_email_sent: 1,
    municipal_email_date: null,
    image_uri: '',
  },
  {
    title: 'Harassment zone near Andheri Station',
    description: 'Multiple women reported eve-teasing incidents between 9 PM - 12 AM. Poorly lit side alleys.',
    category: 'harassment',
    severity: 'critical',
    latitude: 19.1197,
    longitude: 72.8464,
    upvotes: 28,
    status: 'escalated',
    municipal_email_sent: 1,
    municipal_email_date: null,
    image_uri: '',
  },
  {
    title: 'Dimly lit underpass at Juhu',
    description: 'Underpass near beach main gate has zero visibility at night. Students feel unsafe.',
    category: 'unsafe_area',
    severity: 'high',
    latitude: 19.1030,
    longitude: 72.8258,
    upvotes: 9,
    status: 'active',
    municipal_email_sent: 0,
    municipal_email_date: null,
    image_uri: '',
  },
  {
    title: 'Non-functional lights on Marine Drive',
    description: 'Stretch near Chowpatty has 4 dead lights. Dark despite being a commercial zone.',
    category: 'broken_light',
    severity: 'medium',
    latitude: 18.9554,
    longitude: 72.8146,
    upvotes: 7,
    status: 'active',
    municipal_email_sent: 0,
    municipal_email_date: null,
    image_uri: '',
  },
  {
    title: 'Unsafe alley behind Dadar Market',
    description: 'Narrow passage with no lighting or CCTV. Chain-snatching reported twice this month.',
    category: 'unsafe_area',
    severity: 'critical',
    latitude: 19.0195,
    longitude: 72.8425,
    upvotes: 21,
    status: 'municipal_notified',
    municipal_email_sent: 1,
    municipal_email_date: null,
    image_uri: '',
  },
  {
    title: 'Unmanned police booth at Worli Sea Face',
    description: 'Police booth listed as 24/7 but consistently empty after 10 PM.',
    category: 'unresponsive_police',
    severity: 'high',
    latitude: 19.0069,
    longitude: 72.8159,
    upvotes: 16,
    status: 'municipal_notified',
    municipal_email_sent: 1,
    municipal_email_date: null,
    image_uri: '',
  },
];

export const SEED_SAFE_ZONES = [
  {
    name: 'Lilavati Hospital',
    category: 'hospital',
    description: 'Major government hospital with 24/7 emergency ward, trauma center.',
    latitude: 19.0515,
    longitude: 72.8286,
    address: 'Bandra West, Mumbai',
    phone: '022-26666666',
  },
  {
    name: 'Bandra Police Station',
    category: 'police_station',
    description: 'Active police station with dedicated women helpdesk and night patrol.',
    latitude: 19.0553,
    longitude: 72.8340,
    address: 'Bandra West, Mumbai',
    phone: '022-26423048',
  },
  {
    name: 'KEM Hospital Emergency',
    category: 'hospital',
    description: 'Government hospital with 24/7 emergency services.',
    latitude: 19.0041,
    longitude: 72.8407,
    address: 'Parel, Mumbai',
    phone: '022-24136051',
  },
  {
    name: 'Starbucks BKC (24/7)',
    category: '24x7_hotspot',
    description: 'Well-lit 24-hour cafe with high footfall and security guard.',
    latitude: 19.0660,
    longitude: 72.8640,
    address: 'BKC, Mumbai',
    phone: '',
  },
  {
    name: 'Apollo Pharmacy - Andheri',
    category: 'pharmacy',
    description: '24-hour pharmacy, always staffed with CCTV.',
    latitude: 19.1170,
    longitude: 72.8400,
    address: 'Andheri West, Mumbai',
    phone: '022-26578900',
  },
];
