/**
 * Municipal Loop - Mock Email Service
 *
 * In production, this would use Nodemailer/SendGrid to send real emails.
 * For the hackathon demo, it logs to console and returns a success mock.
 */

export const sendMunicipalEmail = async (report) => {
  const emailPayload = {
    to: 'municipal.ahmedabad@gov.example.in',
    from: 'guardian-alerts@projectguardian.app',
    subject: `[URGENT] Safety Report #${report.id}: ${report.title}`,
    body: `
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  PROJECT GUARDIAN - MUNICIPAL SAFETY ALERT
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Report:    ${report.title}
Category:  ${report.category}
Severity:  ${report.severity?.toUpperCase()}
Location:  ${report.latitude}°N, ${report.longitude}°E
Upvotes:   ${report.upvotes} community members
Status:    REQUIRES IMMEDIATE ATTENTION

Description:
${report.description}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
This alert was auto-generated by the Municipal Loop
when this issue reached 10+ community upvotes.
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
    `.trim(),
    sentAt: new Date().toISOString(),
  };

  // Simulate network delay
  await new Promise((resolve) => setTimeout(resolve, 800));

  // Log the "sent" email to console
  console.log('\n╔══════════════════════════════════════════╗');
  console.log('║  MUNICIPAL LOOP EMAIL SENT               ║');
  console.log('╚══════════════════════════════════════════╝');
  console.log(`To: ${emailPayload.to}`);
  console.log(`Subject: ${emailPayload.subject}`);
  console.log(emailPayload.body);
  console.log('─'.repeat(44));

  return {
    success: true,
    messageId: `mock-${Date.now()}-${report.id}`,
    sentAt: emailPayload.sentAt,
    recipient: emailPayload.to,
  };
};
